set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_PLATFORM_TOOLSET "v143")
set(VCPKG_CXX_FLAGS "/std:c++20")
set(VCPKG_C_FLAGS "")

message("VCPKG_PLATFORM_TOOLSET=${VCPKG_PLATFORM_TOOLSET}")
message("VCPKG_CRT_LINKAGE=${VCPKG_CRT_LINKAGE}")
