set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE static)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_PLATFORM_TOOLSET "v142")
set(VCPKG_CXX_FLAGS "/std:c++20")
set(VCPKG_C_FLAGS "")

message("VCPKG_PLATFORM_TOOLSET=${VCPKG_PLATFORM_TOOLSET}")
message("VCPKG_CXX_FLAGS=${VCPKG_CXX_FLAGS}")
