# build examples

add_subdirectory(cpp_sample)

add_subdirectory(c_sample)

add_subdirectory(room_event)

add_subdirectory(publish_audio)

add_subdirectory(publish_microphone)

add_subdirectory(publish_system_audio)

add_subdirectory(publish_video)

add_subdirectory(publish_camera)

add_subdirectory(publish_screen)

add_subdirectory(publish_screen_c)

add_subdirectory(data_transfer)

add_subdirectory(rpc)

add_subdirectory(media_devices)
