local livekit = require("livekit-client")
assert(require("livekit") == livekit)
assert(type(livekit.version()) == "string")
local room, err = livekit.new_room()
assert(room, err)
assert(not room:is_connected())
assert(type(room:state()) == "number")
assert(type(room:sid()) == "string")
assert(type(room:name()) == "string")
assert(type(room:metadata()) == "string")
assert(room:dropped_events() == 0)
assert(room:on(function(_) end))
assert(room:poll() == 0)
local sent, send_error = room:publish_data("\0\1", true, "smoke")
assert(sent == nil and type(send_error) == "string")

local connect_future = assert(room:connect_async("", ""))
local disconnect_future = assert(room:disconnect_async())
local data_future = assert(room:publish_data_async("\0\1", true, "smoke"))
local task = livekit.spawn(function()
  local connected, connect_error = connect_future:await()
  assert(connected == nil and type(connect_error) == "string")
  local disconnected, disconnect_error = disconnect_future:await()
  assert(disconnected == nil and type(disconnect_error) == "string")
  local published, publish_error = data_future:await()
  assert(published == nil and type(publish_error) == "string")
  return "done", nil, 3
end)
for _ = 1, 100 do
  if task:done() then break end
  assert(room:step(50))
end
local finished, first, second, third = task:result()
assert(finished and first == "done" and second == nil and third == 3)

local waited, wait_error = assert(room:connect_async("", "")):wait(50)
assert(waited == nil and type(wait_error) == "string")
local run_result, run_error = livekit.run(room, function()
  return assert(room:publish_data_async("data")):await()
end)
assert(run_result == nil and type(run_error) == "string")
local value, empty, number = livekit.run(room, function() return "value", nil, 3 end)
assert(value == "value" and empty == nil and number == 3)
local crashed, crash_error = livekit.run(room, function() error("coroutine failure") end)
assert(crashed == nil and crash_error:find("coroutine failure", 1, true))

local pending = assert(room:connect_async("", ""))
assert(room:close())
local ready, pending_result, pending_error = pending:result()
assert(ready and pending_result == nil and type(pending_error) == "string")
assert(room:close())
local ok, message = room:connect("ws://localhost:7880", "unused")
assert(ok == nil and message == "room is closed")
room = nil
collectgarbage("collect")
