local livekit = require("livekit-client")
assert(require("livekit") == livekit)
assert(type(livekit.version()) == "string")
assert(livekit.DATA_TRACK_FRAME_ENCODING.JSON == 7)
assert(livekit.DATA_TRACK_SCHEMA_ENCODING.JSON_SCHEMA == 7)
assert(livekit.ICE_TRANSPORT_TYPE.ALL == 3)
assert(livekit.VIDEO_DEGRADATION_PREFERENCE.BALANCED == 2)
local original_log = livekit.log_options()
assert(type(original_log) == "table" and type(original_log.livekit_level) == "number")
assert(livekit.set_log_options({livekit_level = livekit.LOG_DEBUG}))
assert(livekit.log_options().livekit_level == livekit.LOG_DEBUG)
local invalid_log, invalid_log_error = livekit.set_log_options({livekit_level = 99})
assert(invalid_log == nil and type(invalid_log_error) == "string")
local error_info = assert(livekit.last_error_info())
assert(type(error_info.domain) == "number" and type(error_info.code) == "number")
assert(type(error_info.message) == "string")
assert(livekit.ERROR_DOMAIN.STATUS == 1)
assert(livekit.set_log_options(original_log))
local original_trace = livekit.trace_options()
assert(type(original_trace) == "table" and type(original_trace.enabled) == "boolean")
assert(livekit.set_trace_options({enabled = true, category_mask = livekit.TRACE_TRACK + livekit.TRACE_DATA}))
assert(livekit.trace_options().category_mask == livekit.TRACE_TRACK + livekit.TRACE_DATA)
local invalid_trace, invalid_trace_error = livekit.set_trace_options({category_mask = 128})
assert(invalid_trace == nil and type(invalid_trace_error) == "string")
local invalid_file, invalid_file_error = livekit.trace_start_json_file("")
assert(invalid_file == nil and type(invalid_file_error) == "string")
local trace_path = os.tmpname()
os.remove(trace_path)
assert(livekit.trace_start_json_file(trace_path))
assert(livekit.trace_stop())
local trace_file = assert(io.open(trace_path, "rb"))
local trace_contents = trace_file:read("*a")
trace_file:close()
os.remove(trace_path)
assert(trace_contents:find("traceEvents", 1, true))
assert(livekit.set_trace_options(original_trace))
local room, err = livekit.new_room()
assert(room, err)
assert(not room:is_connected())
local unopened_writer, unopened_writer_error = room:stream_text({topic = "smoke"})
assert(unopened_writer == nil and type(unopened_writer_error) == "string")
local async_unopened_writer, async_unopened_error = assert(
  room:stream_bytes_async({topic = "smoke"})):wait(50)
assert(async_unopened_writer == nil and type(async_unopened_error) == "string")
local missing_writer, missing_writer_error = room:stream_writer_info(99999)
assert(missing_writer == nil and missing_writer_error == "stream writer is unavailable")
local missing_write, missing_write_error = room:stream_writer_write(99999, "data")
assert(missing_write == nil and missing_write_error == "stream writer is unavailable")
local missing_data_track, missing_data_track_error = room:data_track_info(99999)
assert(missing_data_track == nil and missing_data_track_error == "local DataTrack is unavailable")
local missing_reader, missing_reader_error = room:read_data_track_frame(99999)
assert(missing_reader == nil and missing_reader_error == "DataTrack reader is unavailable")
assert(type(room:remote_data_tracks()) == "table")
assert(type(room:state()) == "number")
assert(type(room:sid()) == "string")
assert(type(room:name()) == "string")
assert(type(room:metadata()) == "string")
assert(room:register_rpc_method("example.echo", function(request)
  return "echo:" .. request.payload
end))
local duplicate_rpc, duplicate_error = room:register_rpc_method("example.echo", function() end)
assert(duplicate_rpc == nil and type(duplicate_error) == "string")
assert(room:unregister_rpc_method("example.echo"))
assert(room:register_rpc_method("example.echo", function(request)
  return "echo:" .. request.payload
end))
local local_participant = assert(room:local_participant())
assert(type(local_participant.attributes) == "table")
assert(type(room:remote_participants()) == "table")
assert(type(livekit.list_media_devices()) == "table")
local screens, screen_error = livekit.list_screen_sources()
assert(type(screens) == "table" or (screens == nil and type(screen_error) == "string"))
assert(type(room:local_identity()) == "string")
assert(type(room:disconnect_reason()) == "number")
assert(type(room:is_recording()) == "boolean")
assert(room:e2ee_is_configured() == false)
assert(room:e2ee_is_enabled() == false)
local cryptors, cryptors_error = room:e2ee_frame_cryptors()
assert(cryptors == nil and type(cryptors_error) == "string")
local missing_key, missing_key_error = room:e2ee_export_shared_key()
assert(missing_key == nil and type(missing_key_error) == "string")
local key_set, key_set_error = room:e2ee_set_shared_key("\0secret")
assert(key_set == nil and type(key_set_error) == "string")
local subscribed, subscribe_error = room:set_remote_track_subscribed("missing", "missing", true)
assert(subscribed == nil and type(subscribe_error) == "string")
local settings, settings_error = room:update_remote_track_settings("missing", "missing", {enabled = false})
assert(settings == nil and type(settings_error) == "string")
local permissions, permissions_error = room:set_track_subscription_permissions(false, {
  {participant_identity = "allowed", allow_all = false, allowed_track_sids = {"TR_test"}}
})
assert(permissions, permissions_error)
assert(room:set_track_subscription_permissions(true, {}))
assert(type(room:speaker_volume()) == "number")
assert(type(room:speaker_is_muted()) == "boolean")
assert(type(room:audio_playback_stats()) == "table")
local unpublished, unpublished_error = room:publish_audio_track("tone")
assert(unpublished == nil and unpublished_error == "room is not connected")
assert(room:republish_all_tracks())
assert(assert(room:republish_all_tracks_async()):wait(50))
local uncaptured, uncaptured_error = room:publish_microphone_track("mic")
assert(uncaptured == nil and uncaptured_error == "room is not connected")
local async_uncaptured, async_uncaptured_error = assert(
  room:publish_camera_track_async("cam")):wait(50)
assert(async_uncaptured == nil and async_uncaptured_error == "room is not connected")
local invalid_screen, invalid_screen_error = room:publish_screen_track("screen", {})
assert(invalid_screen == nil and invalid_screen_error == "screen source_id is required")
local invalid_queue, invalid_queue_error = room:publish_microphone_track("mic", {queue_ms = 11})
assert(invalid_queue == nil and invalid_queue_error == "queue_ms must be a multiple of 10")
local missing_capture, missing_capture_error = room:capture_is_running(1)
assert(missing_capture == nil and missing_capture_error == "capture track is unavailable")
local missing_microphone, missing_microphone_error = room:microphone_processing_stats(1)
assert(missing_microphone == nil and missing_microphone_error == "microphone track is unavailable")
local missing_stats, missing_stats_error = room:local_track_rtc_stats(1)
assert(missing_stats == nil and missing_stats_error == "local track is unavailable")
local missing_queue, missing_queue_error = room:audio_source_queued_duration_ms(1)
assert(missing_queue == nil and missing_queue_error == "audio track is unavailable")
local missing_encoding, missing_encoding_error = room:update_video_encoding(1, {max_bitrate = 500000})
assert(missing_encoding == nil and missing_encoding_error == "video track is unavailable")
local missing_playout, missing_playout_error = assert(
  room:wait_audio_source_playout_async(1, 0)):wait(50)
assert(missing_playout == nil and missing_playout_error == "audio track is unavailable")
local remote_stats, remote_stats_error = room:remote_track_rtc_stats("missing", "TR_missing")
assert(remote_stats == nil and remote_stats_error == "remote track is unavailable")
local async_unpublished, async_unpublished_error = assert(room:publish_audio_track_async("tone")):wait(50)
assert(async_unpublished == nil and async_unpublished_error == "room is not connected")
local async_subscription, async_subscription_error = assert(
  room:set_remote_track_subscribed_async("PA_missing", "TR_missing", true)):wait(50)
assert(async_subscription == nil and type(async_subscription_error) == "string")
local bad_video, bad_video_error = room:publish_video_track("video", "bad", 2, 2)
assert(bad_video == nil and type(bad_video_error) == "string")
local unstreamed, unstreamed_error = room:open_audio_stream("missing", "TR_missing")
assert(unstreamed == nil and type(unstreamed_error) == "string")
local invalid_attributes, attribute_error = room:set_local_attributes({key = 1})
assert(invalid_attributes == nil and type(attribute_error) == "string")
assert(room:dropped_events() == 0)
assert(room:on(function(_) end))
assert(room:poll() == 0)
local sent, send_error = room:publish_data("\0\1", true, "smoke")
assert(sent == nil and type(send_error) == "string")
local directed, directed_error = room:publish_data_with_options("\0\1", {
  topic = "smoke", destination_identities = {"missing"}
})
assert(directed == nil and type(directed_error) == "string")
local chat_id, chat_error = room:send_chat_message("hello")
assert(chat_id == nil and type(chat_error) == "string")
local text_sent, text_error = room:send_text("hello", "smoke")
assert(text_sent == nil and type(text_error) == "string")
local text_options, text_options_error = room:send_text_with_options("hello", {
  topic = "smoke", attributes = {origin = "lua"}, compress = true
})
assert(text_options == nil and type(text_options_error) == "string")
local bytes_sent, bytes_error = room:send_bytes("\0\1", "smoke")
assert(bytes_sent == nil and type(bytes_error) == "string")
for _, future in ipairs({
  assert(room:send_chat_message_async("hello")),
  assert(room:send_text_async("hello", "smoke")),
  assert(room:send_bytes_async("\0\1", "smoke")),
  assert(room:send_file_async("missing-file", "smoke"))
}) do
  local result, result_error = future:wait(50)
  assert(result == nil and type(result_error) == "string")
end
local rpc, rpc_error = room:perform_rpc("nobody", "echo", "payload", 100)
assert(type(rpc) == "table" and rpc.ok == false and rpc.error_code > 0 and rpc_error == nil)
local async_rpc, async_rpc_error = assert(room:perform_rpc_async("nobody", "echo", "payload", 100)):wait(50)
assert(type(async_rpc) == "table" and async_rpc.ok == false and async_rpc.error_code > 0 and async_rpc_error == nil)

local connect_future = assert(room:connect_async("", ""))
local disconnect_future = assert(room:disconnect_async())
local data_future = assert(room:publish_data_async("\0\1", true, "smoke"))
local task = livekit.spawn(function()
  local connected, connect_error = connect_future:await()
  assert(connected == nil and type(connect_error) == "string")
  local disconnected, disconnect_error = disconnect_future:await()
  assert(disconnected == nil and type(disconnect_error) == "string")
  local published, publish_error = data_future:await()
  assert(published == nil and type(publish_error) == "string")
  return "done", nil, 3
end)
for _ = 1, 100 do
  if task:done() then break end
  assert(room:step(50))
end
local finished, first, second, third = task:result()
assert(finished and first == "done" and second == nil and third == 3)

local waited, wait_error = assert(room:connect_async("", "")):wait(50)
assert(waited == nil and type(wait_error) == "string")
local encrypted, encrypted_error = assert(room:connect_async("", "", {
  e2ee = {enabled = true, shared_key = "\0secret", ratchet_salt = "salt"}
})):wait(50)
assert(encrypted == nil and type(encrypted_error) == "string")
local advanced, advanced_error = assert(room:connect_async("", "", {
  join_retries = 2, reconnect_timeout_ms = 1000,
  continual_gathering_policy = livekit.CONTINUAL_GATHERING_POLICY.GATHER_ONCE,
  ice_transport_type = livekit.ICE_TRANSPORT_TYPE.ALL,
  ice_servers = {{urls = {"stun:stun.example.invalid:3478"}}},
  reconnect_policy = function() return nil end
})):wait(50)
assert(advanced == nil and type(advanced_error) == "string")
local no_token, no_token_error = assert(room:connect_with_token_source_async(function()
  return nil, "no test token"
end)):wait(50)
assert(no_token == nil and type(no_token_error) == "string")
local run_result, run_error = livekit.run(room, function()
  return assert(room:publish_data_async("data")):await()
end)
assert(run_result == nil and type(run_error) == "string")
local value, empty, number = livekit.run(room, function() return "value", nil, 3 end)
assert(value == "value" and empty == nil and number == 3)
local crashed, crash_error = livekit.run(room, function() error("coroutine failure") end)
assert(crashed == nil and crash_error:find("coroutine failure", 1, true))

local pending = assert(room:connect_async("", ""))
assert(room:close())
local ready, pending_result, pending_error = pending:result()
assert(ready and pending_result == nil and type(pending_error) == "string")
assert(room:close())
local ok, message = room:connect("ws://localhost:7880", "unused")
assert(ok == nil and message == "room is closed")
room = nil
collectgarbage("collect")

for _, example in ipairs({"media_devices", "cpp_sample", "room_event", "data_transfer", "stream_writer", "data_track_schema", "token_source", "rpc_caller", "rpc_receiver", "publish_audio", "publish_video", "receive_media", "publish_microphone", "publish_system_audio", "publish_camera", "publish_screen"}) do
  assert(loadfile("pkg/lua/examples/" .. example .. ".lua"))
end
